### ISSUE TITLE
Clean CJS form

### ISSUE THREAD

**Issue by medikoo** [WebReflection/event-target#5]
Currently when requiring in CJS, (according to documentation) one has to do:

```javascript
const EventTarget = require('event-target').default;
```

It'll be way more natural if it's:

```javascript
const EventTarget = require('event-target');
```

Is this fixable?

**Comment by WebReflection** [comment]
Not sure it's worth removing that because every bundler I know uses, and is compatible, with `.default` property via CommonJS imports.

The fact this package is published as dual mode should be relatively temporary, specially being a package mostly used on Web where one would use the standard ESM approach.

**Comment by WebReflection** [comment]
You can `require('event-target/min.js')' without assigning it

**Comment by medikoo** [comment]
> You can require('event-target/min.js') without assigning it.

You mean it will override native (non exensible)`EventTarget` in that case? That sounds pretty dangerous

**Comment by WebReflection** [comment]
> That sounds pretty dangerous

tell me what is dangerous about a constructor you cannot use anyway and indeed you've never used
